pipeline {
    agent any
    stages {
        stage("Init"){
            parallel {
            stage("Hello"){
                agent {docker { image 'mypython:v1' }}
                steps{
                    sh 'python3 src/hello.py'
                }
            }
            stage("wait 30 seconds"){
                steps{
                    sh 'sleep 30'
                    build job:'test', wait : false
                }
            }
        }
        }


    }
}


